vich_uploader:
    db_driver: orm

    mappings:
        shipping_labels:
            uri_prefix: /files/labels
            upload_destination: '%kernel.project_dir%/public/files/labels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer